# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Cyberalien
"""Embed the prepared logo PNGs; uses only the Python standard library."""
from pathlib import Path
import sys

assets, output = map(Path, sys.argv[1:])
lines = ["// Generated by tools/embed_logo.py; do not edit.", "#pragma once", "namespace cy::brand {"]
for size in (16, 24, 32, 48, 64, 128, 256):
    data = (assets / f"logo-{size}.png").read_bytes()
    lines.append(f"inline constexpr unsigned char logo{size}[] = {{")
    lines.extend(
        ",".join(f"0x{byte:02x}" for byte in data[i:i+24]) + ","
        for i in range(0, len(data), 24)
    )
    lines.append("};")
lines.append("}")
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(lines) + "\n", encoding="utf-8")
